import { graphql } from '@/gql'

// Every operation the console uses. Types are generated by `pnpm codegen`
// from x/admin/graph/schema.graphqls.

export const EntityPartsFragment = graphql(`
  fragment EntityParts on Entity {
    name source datasource schema kind description primaryKey uniqueKeys params affects allowCascade tenantPolicy legacyAccess
    mcp { dmlTools customTool trustedProcedure }
    fields { name alias description mask exclude }
    relationships { name target cardinality joinOn }
  }
`)

export const GrantPartsFragment = graphql(`
  fragment GrantParts on Grant { entity actions fieldsRestricted readFields writeFields rows }
`)

export const DatasourcePartsFragment = graphql(`
  fragment DatasourceParts on Datasource {
    name driver dsn readAfterWrite
    connections { name dsn role pooler }
    routing { read write execute }
  }
`)

export const RevisionPartsFragment = graphql(`
  fragment RevisionParts on Revision { id parent state contentHash author comment createdAt publishedAt }
`)

export const WorkspaceQuery = graphql(`
  query Workspace($id: ID!) {
    published { id }
    revision(id: $id) {
      ...RevisionParts
      config {
        datasources { ...DatasourceParts }
        entities { ...EntityParts }
        roles { name description members grants { ...GrantParts } }
        users { name description roles subject disabled hasToken grants { ...GrantParts } }
        settings
      }
    }
  }
`)

export const StatusQuery = graphql(`
  query Status {
    serverStatus { appliedRevision watching pending { id restartRequired error } }
    published { ...RevisionParts }
  }
`)

export const ConfigSchemaQuery = graphql(`
  query ConfigSchema { configSchema }
`)

export const PublishedQuery = graphql(`
  query Published { published { ...RevisionParts } }
`)

export const RevisionsQuery = graphql(`
  query Revisions($limit: Int) { revisions(limit: $limit) { ...RevisionParts } }
`)

export const RevisionHashQuery = graphql(`
  query RevisionHash($id: ID!) {
    revision(id: $id) { id contentHash config { datasources { ...DatasourceParts } } }
  }
`)

export const RevisionYamlQuery = graphql(`
  query RevisionYaml($id: ID!) { revision(id: $id) { id yaml } }
`)

// Importing goes database by database: list the schemas, then scan the one
// opened. A scan runs in the background on the server (start it, then poll);
// the server keeps each schema's last scan until the next one.
export const ImportPartsFragment = graphql(`
  fragment ImportParts on SchemaImport {
    datasource defaultSchema source
    tables {
      schema table description status configuredAs
      columns { name type nullable description primaryKey }
      keys { name columns primary reason }
      indexes { name method parts unique primary where }
      foreignKeys { name columns refSchema refTable refColumns onDelete onUpdate }
      sideEffects
      candidate { ...EntityParts }
    }
  }
`)

// The schema list and the tables of every scanned schema are read together:
// candidate names and relationships span every scanned schema, so the tables
// shown together come from one answer.
export const SchemaSyncQuery = graphql(`
  query SchemaSync($datasource: String!, $refresh: Boolean) {
    schemaList(datasource: $datasource, refresh: $refresh) {
      defaultSchema listedAt source
      schemas { name scannedAt tables }
    }
    schemaTables(datasource: $datasource) { ...ImportParts }
  }
`)

export const StartSchemaScanMutation = graphql(`
  mutation StartSchemaScan($datasource: String!, $schemas: [String!]) {
    startSchemaScan(datasource: $datasource, schemas: $schemas) { id state error }
  }
`)

export const SchemaScanQuery = graphql(`
  query SchemaScan($id: ID!) {
    schemaScan(id: $id) { id state error }
  }
`)

export const CancelSchemaScanMutation = graphql(`
  mutation CancelSchemaScan($id: ID!) { cancelSchemaScan(id: $id) { id state } }
`)

export const TableCommentsQuery = graphql(`
  query TableComments($tables: [TableRef!]!) {
    tableComments(tables: $tables) { description columns { name description } }
  }
`)

export const ValidateQuery = graphql(`
  query Validate($draft: DraftInput!) { validate(draft: $draft) { ok error contentHash restartRequired warnings } }
`)

export const CapabilitiesQuery = graphql(`
  query Capabilities { capabilities { entity action privilege connection columns reason } }
`)

export const DiffQuery = graphql(`
  query Diff($from: ID!, $to: ID, $draft: DraftInput) { diff(from: $from, to: $to, draft: $draft) }
`)

export const SimulateQuery = graphql(`
  query Simulate($input: SimulationInput!) {
    simulate(input: $input) { allowed reason fields rowFilter grants fieldScopes }
  }
`)

export const VisibilityQuery = graphql(`
  query Visibility($input: VisibilityInput!) {
    visibility(input: $input) {
      entity
      actions { action result { allowed reason fields rowFilter grants fieldScopes } }
    }
  }
`)

export const CreateDraftMutation = graphql(`
  mutation CreateDraft($draft: DraftInput!, $comment: String) {
    createDraft(draft: $draft, comment: $comment) { ...RevisionParts }
  }
`)

export const PublishMutation = graphql(`
  mutation Publish($input: PublishInput!) {
    publish(input: $input) { ...RevisionParts }
  }
`)

export const RollbackMutation = graphql(`
  mutation Rollback($input: RollbackInput!) { rollback(input: $input) { ...RevisionParts } }
`)

export const GenerateUserTokenMutation = graphql(`
  mutation GenerateUserToken { generateUserToken { token tokenHash } }
`)

export const AdminAccountsQuery = graphql(`
  query AdminAccounts { adminAccounts { username permissions disabled createdAt updatedAt } }
`)

export const CreateAdminAccountMutation = graphql(`
  mutation CreateAdminAccount($input: AdminAccountInput!) { createAdminAccount(input: $input) { username } }
`)

export const UpdateAdminAccountMutation = graphql(`
  mutation UpdateAdminAccount($input: AdminAccountUpdate!) {
    updateAdminAccount(input: $input) { username permissions disabled }
  }
`)

export const SetAdminPasswordMutation = graphql(`
  mutation SetAdminPassword($input: SetAdminPasswordInput!) { setAdminPassword(input: $input) { username } }
`)
