import { graphql } from '@/gql'

// Every operation the console uses. Types are generated by `pnpm codegen`
// from x/admin/graph/schema.graphqls.

export const EntityPartsFragment = graphql(`
  fragment EntityParts on Entity {
    name source datasource schema kind description primaryKey params tenantPolicy legacyAccess
    mcp { dmlTools customTool trustedProcedure }
    fields { name alias description mask exclude }
    relationships { name target cardinality joinOn }
  }
`)

export const GrantPartsFragment = graphql(`
  fragment GrantParts on Grant { entity actions fieldsRestricted readFields writeFields rows }
`)

export const RevisionPartsFragment = graphql(`
  fragment RevisionParts on Revision { id parent state contentHash author comment createdAt publishedAt }
`)

export const WorkspaceQuery = graphql(`
  query Workspace($id: ID!) {
    published { id }
    revision(id: $id) {
      ...RevisionParts
      config {
        datasources { name driver dsn }
        entities { ...EntityParts }
        roles { name description members grants { ...GrantParts } }
        users { name description roles subject disabled hasToken grants { ...GrantParts } }
        settings
      }
    }
  }
`)

export const StatusQuery = graphql(`
  query Status {
    serverStatus { appliedRevision watching pending { id restartRequired error } }
    published { ...RevisionParts }
  }
`)

export const ConfigSchemaQuery = graphql(`
  query ConfigSchema { configSchema }
`)

export const PublishedQuery = graphql(`
  query Published { published { ...RevisionParts } }
`)

export const RevisionsQuery = graphql(`
  query Revisions($limit: Int) { revisions(limit: $limit) { ...RevisionParts } }
`)

export const RevisionYamlQuery = graphql(`
  query RevisionYaml($id: ID!) { revision(id: $id) { id yaml } }
`)

export const SchemaImportQuery = graphql(`
  query SchemaImport($datasource: String!, $schemas: [String!]) {
    schemaImport(datasource: $datasource, schemas: $schemas) {
      datasource
      tables {
        schema table description status configuredAs addedColumns missingColumns
        columns { name type nullable description primaryKey }
        candidate { ...EntityParts }
      }
    }
  }
`)

export const ValidateQuery = graphql(`
  query Validate($draft: DraftInput!) { validate(draft: $draft) { ok error contentHash restartRequired } }
`)

export const DiffQuery = graphql(`
  query Diff($from: ID!, $to: ID, $draft: DraftInput) { diff(from: $from, to: $to, draft: $draft) }
`)

export const SimulateQuery = graphql(`
  query Simulate($input: SimulationInput!) {
    simulate(input: $input) { allowed reason fields rowFilter grants fieldScopes }
  }
`)

export const VisibilityQuery = graphql(`
  query Visibility($input: VisibilityInput!) {
    visibility(input: $input) {
      entity
      actions { action result { allowed reason fields rowFilter grants fieldScopes } }
    }
  }
`)

export const CreateDraftMutation = graphql(`
  mutation CreateDraft($draft: DraftInput!, $comment: String) {
    createDraft(draft: $draft, comment: $comment) { ...RevisionParts }
  }
`)

export const PublishMutation = graphql(`
  mutation Publish($input: PublishInput!) {
    publish(input: $input) { ...RevisionParts }
  }
`)

export const RollbackMutation = graphql(`
  mutation Rollback($input: RollbackInput!) { rollback(input: $input) { ...RevisionParts } }
`)

export const GenerateUserTokenMutation = graphql(`
  mutation GenerateUserToken { generateUserToken { token tokenHash } }
`)

export const AdminAccountsQuery = graphql(`
  query AdminAccounts { adminAccounts { username permissions disabled createdAt updatedAt } }
`)

export const CreateAdminAccountMutation = graphql(`
  mutation CreateAdminAccount($input: AdminAccountInput!) { createAdminAccount(input: $input) { username } }
`)

export const UpdateAdminAccountMutation = graphql(`
  mutation UpdateAdminAccount($input: AdminAccountUpdate!) {
    updateAdminAccount(input: $input) { username permissions disabled }
  }
`)

export const SetAdminPasswordMutation = graphql(`
  mutation SetAdminPassword($input: SetAdminPasswordInput!) { setAdminPassword(input: $input) { username } }
`)
