-- Generated by fixtures/v4/generator (seed=1 scale=1). Do not edit;
-- run `make fixtures-v4` to regenerate.
DROP TABLE IF EXISTS wl_ledger_accounts;
CREATE TABLE wl_ledger_accounts (
	id integer NOT NULL,
	account_type varchar(64) NOT NULL,
	owner_ref varchar(64) NOT NULL,
	currency_code varchar(64) NOT NULL,
	PRIMARY KEY (id)
);

DROP TABLE IF EXISTS wl_fee_rule_versions;
CREATE TABLE wl_fee_rule_versions (
	id integer NOT NULL,
	channel_id integer NOT NULL,
	fee_bps integer NOT NULL,
	valid_from date NOT NULL,
	valid_to date,
	PRIMARY KEY (id)
);

DROP TABLE IF EXISTS wl_ledger_transactions;
CREATE TABLE wl_ledger_transactions (
	id integer NOT NULL,
	source_type varchar(64) NOT NULL,
	source_id integer NOT NULL,
	status varchar(64) NOT NULL,
	posted_at timestamp NOT NULL,
	PRIMARY KEY (id)
);

DROP TABLE IF EXISTS wl_ledger_entries;
CREATE TABLE wl_ledger_entries (
	id integer NOT NULL,
	transaction_id integer NOT NULL,
	account_id integer NOT NULL,
	direction varchar(64) NOT NULL,
	amount_minor bigint NOT NULL,
	currency_code varchar(64) NOT NULL,
	PRIMARY KEY (id)
);

DROP TABLE IF EXISTS wl_settlements;
CREATE TABLE wl_settlements (
	id integer NOT NULL,
	organization_id integer NOT NULL,
	period_start date NOT NULL,
	period_end date NOT NULL,
	gross_minor bigint NOT NULL,
	fee_minor bigint NOT NULL,
	refund_minor bigint NOT NULL,
	net_minor bigint NOT NULL,
	currency_code varchar(64) NOT NULL,
	status varchar(64) NOT NULL,
	settled_at timestamp NOT NULL,
	PRIMARY KEY (id)
);

DROP TABLE IF EXISTS wl_external_statement_items;
CREATE TABLE wl_external_statement_items (
	id integer NOT NULL,
	channel_id integer NOT NULL,
	external_ref varchar(64) NOT NULL,
	amount_minor bigint NOT NULL,
	currency_code varchar(64) NOT NULL,
	statement_date date NOT NULL,
	PRIMARY KEY (id)
);

DROP TABLE IF EXISTS wl_reconciliation_results;
CREATE TABLE wl_reconciliation_results (
	id integer NOT NULL,
	intent_id integer,
	statement_item_id integer,
	status varchar(64) NOT NULL,
	difference_minor bigint NOT NULL,
	checked_at timestamp NOT NULL,
	PRIMARY KEY (id)
);

DROP TABLE IF EXISTS wl_balance_snapshots;
CREATE TABLE wl_balance_snapshots (
	id integer NOT NULL,
	account_id integer NOT NULL,
	snapshot_date date NOT NULL,
	balance_minor bigint NOT NULL,
	currency_code varchar(64) NOT NULL,
	PRIMARY KEY (id)
);
