// Package graph implements the admin GraphQL API. The schema lives in
// schema.graphqls; generated.go and models_gen.go are generated by gqlgen.
package graph

//go:generate go tool gqlgen generate --config gqlgen.yml
//go:generate go run github.com/segmentio/golines@v0.13.0 -w -m 120 --base-formatter gofmt schema.resolvers.go
