// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

type ActionVisibility struct {
	Action Action      `json:"action"`
	Result *Simulation `json:"result"`
}

type AdminAccount struct {
	Username    string    `json:"username"`
	Permissions []string  `json:"permissions"`
	Disabled    bool      `json:"disabled"`
	CreatedAt   time.Time `json:"createdAt"`
	UpdatedAt   time.Time `json:"updatedAt"`
}

type AdminAccountInput struct {
	Username    string   `json:"username"`
	Password    string   `json:"password"`
	Permissions []string `json:"permissions"`
}

type AdminAccountUpdate struct {
	Username    string   `json:"username"`
	Permissions []string `json:"permissions,omitempty"`
	Disabled    *bool    `json:"disabled,omitempty"`
}

type ColumnComment struct {
	Name        string `json:"name"`
	Description string `json:"description"`
}

type Configuration struct {
	Datasources []Datasource `json:"datasources"`
	Entities    []Entity     `json:"entities"`
	Roles       []Role       `json:"roles"`
	Users       []User       `json:"users"`
	// Every other top-level section (server, tools, cost, budget, cache, ...) as YAML-shaped JSON.
	Settings any `json:"settings"`
}

type Datasource struct {
	Name   string `json:"name"`
	Driver string `json:"driver"`
	// The read connection's DSN with passwords redacted.
	Dsn         string                 `json:"dsn"`
	Connections []DatasourceConnection `json:"connections"`
	// The connection reads, writes and procedure calls use.
	Routing *DatasourceRouting `json:"routing"`
	// How long a session reads from the write connection after writing (a Go duration); empty when off.
	ReadAfterWrite *string `json:"readAfterWrite,omitempty"`
}

type DatasourceConnection struct {
	Name string `json:"name"`
	// The DSN with passwords redacted.
	Dsn string `json:"dsn"`
	// primary or replica.
	Role string `json:"role"`
	// transaction behind a transaction-mode pooler; null otherwise.
	Pooler *string `json:"pooler,omitempty"`
}

type DatasourceRouting struct {
	Read    string `json:"read"`
	Write   string `json:"write"`
	Execute string `json:"execute"`
}

type DraftInput struct {
	Base string `json:"base"`
	// Replaces the entities section when provided.
	Entities []EntityInput `json:"entities,omitempty"`
	// Replaces the roles section when provided.
	Roles []RoleInput `json:"roles,omitempty"`
	// Replaces the users section when provided; a missing tokenHash keeps the base user's hash.
	Users []UserInput `json:"users,omitempty"`
	// Replaces the given top-level sections; datasources, entities, roles and users are not allowed here.
	Settings any `json:"settings,omitempty"`
}

type Entity struct {
	Name string `json:"name"`
	// The table, view or procedure; null means the entity name.
	Source *string `json:"source,omitempty"`
	// null means the datasource named default.
	Datasource *string `json:"datasource,omitempty"`
	Schema     *string `json:"schema,omitempty"`
	// table, view or procedure; null means table.
	Kind        *string  `json:"kind,omitempty"`
	Description *string  `json:"description,omitempty"`
	PrimaryKey  []string `json:"primaryKey"`
	// Unique keys, each a field list, that identify one row like the primary key.
	UniqueKeys    [][]string     `json:"uniqueKeys"`
	Fields        []Field        `json:"fields"`
	Relationships []Relationship `json:"relationships"`
	TenantPolicy  any            `json:"tenantPolicy,omitempty"`
	// Entity-level roles, fieldACL and rowPolicies, kept for compatibility.
	LegacyAccess any        `json:"legacyAccess,omitempty"`
	Mcp          *EntityMcp `json:"mcp"`
	Params       []string   `json:"params"`
	// Entities a procedure writes; empty invalidates its datasource's cached reads.
	Affects []string `json:"affects"`
	// Admit deletes and key updates that foreign keys cascade to other tables without checking permissions there.
	AllowCascade bool `json:"allowCascade"`
}

type EntityCapability struct {
	Entity    string    `json:"entity"`
	Action    Action    `json:"action"`
	Privilege Privilege `json:"privilege"`
	// The connection the action routes to.
	Connection string `json:"connection"`
	// Columns granted at column level when the table-level privilege is not.
	Columns []string `json:"columns,omitempty"`
	Reason  *string  `json:"reason,omitempty"`
}

type EntityInput struct {
	Name          string              `json:"name"`
	Source        *string             `json:"source,omitempty"`
	Datasource    *string             `json:"datasource,omitempty"`
	Schema        *string             `json:"schema,omitempty"`
	Kind          *string             `json:"kind,omitempty"`
	Description   *string             `json:"description,omitempty"`
	PrimaryKey    []string            `json:"primaryKey,omitempty"`
	UniqueKeys    [][]string          `json:"uniqueKeys,omitempty"`
	Fields        []FieldInput        `json:"fields,omitempty"`
	Relationships []RelationshipInput `json:"relationships,omitempty"`
	TenantPolicy  any                 `json:"tenantPolicy,omitempty"`
	LegacyAccess  any                 `json:"legacyAccess,omitempty"`
	Mcp           *EntityMCPInput     `json:"mcp,omitempty"`
	Params        []string            `json:"params,omitempty"`
	Affects       []string            `json:"affects,omitempty"`
	AllowCascade  *bool               `json:"allowCascade,omitempty"`
}

type EntityMcp struct {
	DmlTools         bool `json:"dmlTools"`
	CustomTool       bool `json:"customTool"`
	TrustedProcedure bool `json:"trustedProcedure"`
}

type EntityMCPInput struct {
	DmlTools         *bool `json:"dmlTools,omitempty"`
	CustomTool       *bool `json:"customTool,omitempty"`
	TrustedProcedure *bool `json:"trustedProcedure,omitempty"`
}

type EntityVisibility struct {
	Entity string `json:"entity"`
	// One result per action that applies to the entity kind.
	Actions []ActionVisibility `json:"actions"`
}

type Field struct {
	Name        string  `json:"name"`
	Alias       *string `json:"alias,omitempty"`
	Description *string `json:"description,omitempty"`
	Mask        *string `json:"mask,omitempty"`
	Exclude     bool    `json:"exclude"`
}

type FieldInput struct {
	Name        string  `json:"name"`
	Alias       *string `json:"alias,omitempty"`
	Description *string `json:"description,omitempty"`
	Mask        *string `json:"mask,omitempty"`
	Exclude     *bool   `json:"exclude,omitempty"`
}

type Grant struct {
	Entity  string   `json:"entity"`
	Actions []Action `json:"actions"`
	// False grants every visible field; true limits to readFields/writeFields.
	FieldsRestricted bool     `json:"fieldsRestricted"`
	ReadFields       []string `json:"readFields"`
	WriteFields      []string `json:"writeFields"`
	Rows             any      `json:"rows,omitempty"`
}

type GrantInput struct {
	Entity           string   `json:"entity"`
	Actions          []Action `json:"actions"`
	FieldsRestricted *bool    `json:"fieldsRestricted,omitempty"`
	ReadFields       []string `json:"readFields,omitempty"`
	WriteFields      []string `json:"writeFields,omitempty"`
	Rows             any      `json:"rows,omitempty"`
}

type ImportColumn struct {
	Name        string `json:"name"`
	Type        string `json:"type"`
	Nullable    bool   `json:"nullable"`
	Description string `json:"description"`
	PrimaryKey  bool   `json:"primaryKey"`
}

type ImportForeignKey struct {
	Name       string   `json:"name"`
	Columns    []string `json:"columns"`
	RefSchema  string   `json:"refSchema"`
	RefTable   string   `json:"refTable"`
	RefColumns []string `json:"refColumns"`
	// Referential action that writes referencing rows (cascade, set_null, set_default); null when it only checks.
	OnDelete *string `json:"onDelete,omitempty"`
	OnUpdate *string `json:"onUpdate,omitempty"`
}

type ImportIndex struct {
	Name string `json:"name"`
	// The database's name for the index structure, lower-cased: for example
	// btree, hash, gin, gist, brin, spgist (PostgreSQL); btree, hash, fulltext,
	// spatial (MySQL, OceanBase).
	Method string `json:"method"`
	// Key parts in order: a column, a column prefix such as title(20), or an
	// expression as the database prints it; parts the database does not report
	// are left out (empty when it reports none).
	Parts   []string `json:"parts"`
	Unique  bool     `json:"unique"`
	Primary bool     `json:"primary"`
	// The predicate of a partial index; null for a full one.
	Where *string `json:"where,omitempty"`
}

type ImportKey struct {
	Name    string   `json:"name"`
	Columns []string `json:"columns"`
	Primary bool     `json:"primary"`
	// Why the key cannot identify a row (partial, expression, prefix, nullable); null when it can.
	Reason *string `json:"reason,omitempty"`
}

type ImportTable struct {
	Schema      string       `json:"schema"`
	Table       string       `json:"table"`
	Description string       `json:"description"`
	Status      ImportStatus `json:"status"`
	// The configured entity name when status is CONFIGURED.
	ConfiguredAs *string        `json:"configuredAs,omitempty"`
	Columns      []ImportColumn `json:"columns"`
	// The primary key and unique keys, including those that cannot identify a row.
	Keys []ImportKey `json:"keys"`
	// Every index, in the database's own terms; the unique ones are also keys.
	Indexes     []ImportIndex      `json:"indexes"`
	ForeignKeys []ImportForeignKey `json:"foreignKeys"`
	// Triggers or rules: a write may change other tables.
	SideEffects bool `json:"sideEffects"`
	// A zero-permission entity proposal; add it to a draft to configure it.
	Candidate *Entity `json:"candidate"`
}

type Mutation struct {
}

type PendingRevision struct {
	ID string `json:"id"`
	// True when only a restart applies it; otherwise building it failed.
	RestartRequired bool   `json:"restartRequired"`
	Error           string `json:"error"`
}

type PublishInput struct {
	// The draft to publish.
	ID              string `json:"id"`
	RestartRequired *bool  `json:"restartRequired,omitempty"`
	// The published revision the caller based its work on; when another revision
	// was published since, publish fails with extensions.code CONFLICT.
	ExpectedPublished *string `json:"expectedPublished,omitempty"`
}

type Query struct {
}

type Relationship struct {
	Name        string `json:"name"`
	Target      string `json:"target"`
	Cardinality string `json:"cardinality"`
	JoinOn      any    `json:"joinOn"`
}

type RelationshipInput struct {
	Name        string `json:"name"`
	Target      string `json:"target"`
	Cardinality string `json:"cardinality"`
	JoinOn      any    `json:"joinOn"`
}

type Role struct {
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
	Grants      []Grant `json:"grants"`
	// Users that have this role.
	Members []string `json:"members"`
}

type RoleInput struct {
	Name        string       `json:"name"`
	Description *string      `json:"description,omitempty"`
	Grants      []GrantInput `json:"grants,omitempty"`
}

type RollbackInput struct {
	// Revision to restore; default: the newest earlier published content.
	To              *string `json:"to,omitempty"`
	RestartRequired *bool   `json:"restartRequired,omitempty"`
	Comment         *string `json:"comment,omitempty"`
}

type ScanJob struct {
	ID         string    `json:"id"`
	Datasource string    `json:"datasource"`
	State      ScanState `json:"state"`
	// Why the scan failed or stopped.
	Error *string `json:"error,omitempty"`
}

type SchemaImport struct {
	Datasource string `json:"datasource"`
	// The schema where entities without a schema read (unqualified names
	// resolve); null when the database cannot report it.
	DefaultSchema *string       `json:"defaultSchema,omitempty"`
	Tables        []ImportTable `json:"tables"`
	// Identifies the database the datasource reads (its driver and read
	// connection); results of another source are stale.
	Source string `json:"source"`
}

type SchemaInfo struct {
	Name string `json:"name"`
	// When its tables were last scanned; null when never.
	ScannedAt *time.Time `json:"scannedAt,omitempty"`
	// How many tables the last scan found; null when never scanned.
	Tables *int `json:"tables,omitempty"`
}

type SchemaList struct {
	Datasource string `json:"datasource"`
	// Every user schema; when the database cannot list them, one named "" for its
	// default schema, which a scan without schemas reads.
	Schemas []SchemaInfo `json:"schemas"`
	// Where unqualified names resolve; null when unknown.
	DefaultSchema *string   `json:"defaultSchema,omitempty"`
	ListedAt      time.Time `json:"listedAt"`
	// Identifies the database the datasource reads (its driver and read
	// connection); results of another source are stale.
	Source string `json:"source"`
}

type ServerStatus struct {
	// Revision this process serves; null when it does not track the store.
	AppliedRevision *string `json:"appliedRevision,omitempty"`
	// Whether the process applies newly published revisions (--watch).
	Watching bool `json:"watching"`
	// A published revision this process has not applied.
	Pending *PendingRevision `json:"pending,omitempty"`
}

type SetAdminPasswordInput struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type Simulation struct {
	Allowed bool     `json:"allowed"`
	Reason  string   `json:"reason"`
	Fields  []string `json:"fields"`
	// Effective row filter in rowPolicies JSON form; null means every row.
	RowFilter any      `json:"rowFilter,omitempty"`
	Grants    []string `json:"grants"`
	// Set when no single grant covers the requested fields.
	FieldScopes [][]string `json:"fieldScopes,omitempty"`
}

type SimulationInput struct {
	// Simulate against this unsaved draft...
	Draft *DraftInput `json:"draft,omitempty"`
	// ...or this revision; default: the published revision.
	Revision *string `json:"revision,omitempty"`
	// A configured user name, or role:<name> to evaluate a role.
	User   string `json:"user"`
	Entity string `json:"entity"`
	Action Action `json:"action"`
	// Requested fields; empty means the default projection.
	Fields []string `json:"fields,omitempty"`
	// Extra subject attributes; configured user attributes win.
	Subject any `json:"subject,omitempty"`
}

type TableComments struct {
	Description string          `json:"description"`
	Columns     []ColumnComment `json:"columns"`
}

type TableRef struct {
	Datasource string  `json:"datasource"`
	Schema     *string `json:"schema,omitempty"`
	// Physical table name (entity source).
	Table string `json:"table"`
}

type User struct {
	Name        string   `json:"name"`
	Description *string  `json:"description,omitempty"`
	Roles       []string `json:"roles"`
	Grants      []Grant  `json:"grants"`
	Subject     any      `json:"subject,omitempty"`
	Disabled    bool     `json:"disabled"`
	HasToken    bool     `json:"hasToken"`
}

type UserInput struct {
	Name        string       `json:"name"`
	Description *string      `json:"description,omitempty"`
	Roles       []string     `json:"roles,omitempty"`
	Grants      []GrantInput `json:"grants,omitempty"`
	Subject     any          `json:"subject,omitempty"`
	Disabled    *bool        `json:"disabled,omitempty"`
	TokenHash   *string      `json:"tokenHash,omitempty"`
}

type UserToken struct {
	Token     string `json:"token"`
	TokenHash string `json:"tokenHash"`
}

type Validation struct {
	Ok          bool    `json:"ok"`
	Error       *string `json:"error,omitempty"`
	ContentHash *string `json:"contentHash,omitempty"`
	// Changes against the published revision that need a restart.
	RestartRequired []string `json:"restartRequired"`
	// Grants the routed datasource connections cannot run (they do not block publishing).
	Warnings []string `json:"warnings"`
}

type VisibilityInput struct {
	Draft    *DraftInput `json:"draft,omitempty"`
	Revision *string     `json:"revision,omitempty"`
	// A configured user name, or role:<name> to evaluate a role.
	User    string `json:"user"`
	Subject any    `json:"subject,omitempty"`
}

type Action string

const (
	ActionRead      Action = "READ"
	ActionCreate    Action = "CREATE"
	ActionUpdate    Action = "UPDATE"
	ActionDelete    Action = "DELETE"
	ActionExecute   Action = "EXECUTE"
	ActionAggregate Action = "AGGREGATE"
)

var AllAction = []Action{
	ActionRead,
	ActionCreate,
	ActionUpdate,
	ActionDelete,
	ActionExecute,
	ActionAggregate,
}

func (e Action) IsValid() bool {
	switch e {
	case ActionRead, ActionCreate, ActionUpdate, ActionDelete, ActionExecute, ActionAggregate:
		return true
	}
	return false
}

func (e Action) String() string {
	return string(e)
}

func (e *Action) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Action(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Action", str)
	}
	return nil
}

func (e Action) MarshalGQL(w io.Writer) {
	_, _ = fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Action) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Action) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ImportStatus string

const (
	// No configured entity reads this table.
	ImportStatusNew ImportStatus = "NEW"
	// An entity of the same datasource already reads this table.
	ImportStatusConfigured ImportStatus = "CONFIGURED"
)

var AllImportStatus = []ImportStatus{
	ImportStatusNew,
	ImportStatusConfigured,
}

func (e ImportStatus) IsValid() bool {
	switch e {
	case ImportStatusNew, ImportStatusConfigured:
		return true
	}
	return false
}

func (e ImportStatus) String() string {
	return string(e)
}

func (e *ImportStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ImportStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ImportStatus", str)
	}
	return nil
}

func (e ImportStatus) MarshalGQL(w io.Writer) {
	_, _ = fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ImportStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ImportStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type Privilege string

const (
	PrivilegeGranted Privilege = "GRANTED"
	PrivilegeDenied  Privilege = "DENIED"
	PrivilegeUnknown Privilege = "UNKNOWN"
)

var AllPrivilege = []Privilege{
	PrivilegeGranted,
	PrivilegeDenied,
	PrivilegeUnknown,
}

func (e Privilege) IsValid() bool {
	switch e {
	case PrivilegeGranted, PrivilegeDenied, PrivilegeUnknown:
		return true
	}
	return false
}

func (e Privilege) String() string {
	return string(e)
}

func (e *Privilege) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Privilege(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Privilege", str)
	}
	return nil
}

func (e Privilege) MarshalGQL(w io.Writer) {
	_, _ = fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Privilege) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Privilege) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type RevisionState string

const (
	RevisionStateDraft      RevisionState = "DRAFT"
	RevisionStatePublished  RevisionState = "PUBLISHED"
	RevisionStateSuperseded RevisionState = "SUPERSEDED"
	RevisionStateRolledBack RevisionState = "ROLLED_BACK"
)

var AllRevisionState = []RevisionState{
	RevisionStateDraft,
	RevisionStatePublished,
	RevisionStateSuperseded,
	RevisionStateRolledBack,
}

func (e RevisionState) IsValid() bool {
	switch e {
	case RevisionStateDraft, RevisionStatePublished, RevisionStateSuperseded, RevisionStateRolledBack:
		return true
	}
	return false
}

func (e RevisionState) String() string {
	return string(e)
}

func (e *RevisionState) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = RevisionState(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid RevisionState", str)
	}
	return nil
}

func (e RevisionState) MarshalGQL(w io.Writer) {
	_, _ = fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *RevisionState) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e RevisionState) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ScanState string

const (
	ScanStatePending  ScanState = "PENDING"
	ScanStateRunning  ScanState = "RUNNING"
	ScanStateDone     ScanState = "DONE"
	ScanStateFailed   ScanState = "FAILED"
	ScanStateCanceled ScanState = "CANCELED"
)

var AllScanState = []ScanState{
	ScanStatePending,
	ScanStateRunning,
	ScanStateDone,
	ScanStateFailed,
	ScanStateCanceled,
}

func (e ScanState) IsValid() bool {
	switch e {
	case ScanStatePending, ScanStateRunning, ScanStateDone, ScanStateFailed, ScanStateCanceled:
		return true
	}
	return false
}

func (e ScanState) String() string {
	return string(e)
}

func (e *ScanState) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ScanState(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ScanState", str)
	}
	return nil
}

func (e ScanState) MarshalGQL(w io.Writer) {
	_, _ = fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ScanState) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ScanState) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
