// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

type ActionVisibility struct {
	Action Action      `json:"action"`
	Result *Simulation `json:"result"`
}

type AdminAccount struct {
	Username    string    `json:"username"`
	Permissions []string  `json:"permissions"`
	Disabled    bool      `json:"disabled"`
	CreatedAt   time.Time `json:"createdAt"`
	UpdatedAt   time.Time `json:"updatedAt"`
}

type AdminAccountInput struct {
	Username    string   `json:"username"`
	Password    string   `json:"password"`
	Permissions []string `json:"permissions"`
}

type AdminAccountUpdate struct {
	Username    string   `json:"username"`
	Permissions []string `json:"permissions,omitempty"`
	Disabled    *bool    `json:"disabled,omitempty"`
}

type Configuration struct {
	Datasources []Datasource `json:"datasources"`
	Entities    []Entity     `json:"entities"`
	Roles       []Role       `json:"roles"`
	Users       []User       `json:"users"`
	// Every other top-level section (server, tools, cost, budget, cache, ...) as YAML-shaped JSON.
	Settings any `json:"settings"`
}

type Datasource struct {
	Name   string `json:"name"`
	Driver string `json:"driver"`
	// The DSN with passwords redacted.
	Dsn string `json:"dsn"`
}

type DraftInput struct {
	Base string `json:"base"`
	// Replaces the entities section when provided.
	Entities []EntityInput `json:"entities,omitempty"`
	// Replaces the roles section when provided.
	Roles []RoleInput `json:"roles,omitempty"`
	// Replaces the users section when provided; a missing tokenHash keeps the base user's hash.
	Users []UserInput `json:"users,omitempty"`
	// Replaces the given top-level sections; datasources, entities, roles and users are not allowed here.
	Settings any `json:"settings,omitempty"`
}

type Entity struct {
	Name          string         `json:"name"`
	Source        string         `json:"source"`
	Datasource    string         `json:"datasource"`
	Schema        *string        `json:"schema,omitempty"`
	Kind          string         `json:"kind"`
	Description   *string        `json:"description,omitempty"`
	PrimaryKey    []string       `json:"primaryKey"`
	Fields        []Field        `json:"fields"`
	Relationships []Relationship `json:"relationships"`
	TenantPolicy  any            `json:"tenantPolicy,omitempty"`
	// Entity-level roles, fieldACL and rowPolicies, kept for compatibility.
	LegacyAccess any        `json:"legacyAccess,omitempty"`
	Mcp          *EntityMcp `json:"mcp"`
	Params       []string   `json:"params"`
}

type EntityInput struct {
	Name          string              `json:"name"`
	Source        *string             `json:"source,omitempty"`
	Datasource    *string             `json:"datasource,omitempty"`
	Schema        *string             `json:"schema,omitempty"`
	Kind          *string             `json:"kind,omitempty"`
	Description   *string             `json:"description,omitempty"`
	PrimaryKey    []string            `json:"primaryKey,omitempty"`
	Fields        []FieldInput        `json:"fields,omitempty"`
	Relationships []RelationshipInput `json:"relationships,omitempty"`
	TenantPolicy  any                 `json:"tenantPolicy,omitempty"`
	LegacyAccess  any                 `json:"legacyAccess,omitempty"`
	Mcp           *EntityMCPInput     `json:"mcp,omitempty"`
	Params        []string            `json:"params,omitempty"`
}

type EntityMcp struct {
	DmlTools         bool `json:"dmlTools"`
	CustomTool       bool `json:"customTool"`
	TrustedProcedure bool `json:"trustedProcedure"`
}

type EntityMCPInput struct {
	DmlTools         *bool `json:"dmlTools,omitempty"`
	CustomTool       *bool `json:"customTool,omitempty"`
	TrustedProcedure *bool `json:"trustedProcedure,omitempty"`
}

type EntityVisibility struct {
	Entity string `json:"entity"`
	// One result per action that applies to the entity kind.
	Actions []ActionVisibility `json:"actions"`
}

type Field struct {
	Name        string  `json:"name"`
	Alias       *string `json:"alias,omitempty"`
	Description *string `json:"description,omitempty"`
	Mask        *string `json:"mask,omitempty"`
	Exclude     bool    `json:"exclude"`
}

type FieldInput struct {
	Name        string  `json:"name"`
	Alias       *string `json:"alias,omitempty"`
	Description *string `json:"description,omitempty"`
	Mask        *string `json:"mask,omitempty"`
	Exclude     *bool   `json:"exclude,omitempty"`
}

type Grant struct {
	Entity  string   `json:"entity"`
	Actions []Action `json:"actions"`
	// False grants every visible field; true limits to readFields/writeFields.
	FieldsRestricted bool     `json:"fieldsRestricted"`
	ReadFields       []string `json:"readFields"`
	WriteFields      []string `json:"writeFields"`
	Rows             any      `json:"rows,omitempty"`
}

type GrantInput struct {
	Entity           string   `json:"entity"`
	Actions          []Action `json:"actions"`
	FieldsRestricted *bool    `json:"fieldsRestricted,omitempty"`
	ReadFields       []string `json:"readFields,omitempty"`
	WriteFields      []string `json:"writeFields,omitempty"`
	Rows             any      `json:"rows,omitempty"`
}

type ImportColumn struct {
	Name        string `json:"name"`
	Type        string `json:"type"`
	Nullable    bool   `json:"nullable"`
	Description string `json:"description"`
	PrimaryKey  bool   `json:"primaryKey"`
}

type ImportTable struct {
	Schema      string       `json:"schema"`
	Table       string       `json:"table"`
	Description string       `json:"description"`
	Status      ImportStatus `json:"status"`
	// The configured entity name when status is CONFIGURED.
	ConfiguredAs *string `json:"configuredAs,omitempty"`
	// Database columns the configured entity does not declare.
	AddedColumns []string `json:"addedColumns"`
	// Columns the configured entity declares that the database lacks.
	MissingColumns []string       `json:"missingColumns"`
	Columns        []ImportColumn `json:"columns"`
	// A zero-permission entity proposal; add it to a draft to configure it.
	Candidate *Entity `json:"candidate"`
}

type Mutation struct {
}

type PendingRevision struct {
	ID string `json:"id"`
	// True when only a restart applies it; otherwise building it failed.
	RestartRequired bool   `json:"restartRequired"`
	Error           string `json:"error"`
}

type PublishInput struct {
	// The draft to publish.
	ID              string `json:"id"`
	RestartRequired *bool  `json:"restartRequired,omitempty"`
	// The published revision the caller based its work on; when another revision
	// was published since, publish fails with extensions.code CONFLICT.
	ExpectedPublished *string `json:"expectedPublished,omitempty"`
}

type Query struct {
}

type Relationship struct {
	Name        string `json:"name"`
	Target      string `json:"target"`
	Cardinality string `json:"cardinality"`
	JoinOn      any    `json:"joinOn"`
}

type RelationshipInput struct {
	Name        string `json:"name"`
	Target      string `json:"target"`
	Cardinality string `json:"cardinality"`
	JoinOn      any    `json:"joinOn"`
}

type Role struct {
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
	Grants      []Grant `json:"grants"`
	// Users that have this role.
	Members []string `json:"members"`
}

type RoleInput struct {
	Name        string       `json:"name"`
	Description *string      `json:"description,omitempty"`
	Grants      []GrantInput `json:"grants,omitempty"`
}

type RollbackInput struct {
	// Revision to restore; default: the newest earlier published content.
	To              *string `json:"to,omitempty"`
	RestartRequired *bool   `json:"restartRequired,omitempty"`
	Comment         *string `json:"comment,omitempty"`
}

type SchemaImport struct {
	Datasource string        `json:"datasource"`
	Tables     []ImportTable `json:"tables"`
}

type ServerStatus struct {
	// Revision this process serves; null when it does not track the store.
	AppliedRevision *string `json:"appliedRevision,omitempty"`
	// Whether the process applies newly published revisions (--watch).
	Watching bool `json:"watching"`
	// A published revision this process has not applied.
	Pending *PendingRevision `json:"pending,omitempty"`
}

type SetAdminPasswordInput struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type Simulation struct {
	Allowed bool     `json:"allowed"`
	Reason  string   `json:"reason"`
	Fields  []string `json:"fields"`
	// Effective row filter in rowPolicies JSON form; null means every row.
	RowFilter any      `json:"rowFilter,omitempty"`
	Grants    []string `json:"grants"`
	// Set when no single grant covers the requested fields.
	FieldScopes [][]string `json:"fieldScopes,omitempty"`
}

type SimulationInput struct {
	// Simulate against this unsaved draft...
	Draft *DraftInput `json:"draft,omitempty"`
	// ...or this revision; default: the published revision.
	Revision *string `json:"revision,omitempty"`
	// A configured user name, or role:<name> to evaluate a role.
	User   string `json:"user"`
	Entity string `json:"entity"`
	Action Action `json:"action"`
	// Requested fields; empty means the default projection.
	Fields []string `json:"fields,omitempty"`
	// Extra subject attributes; configured user attributes win.
	Subject any `json:"subject,omitempty"`
}

type User struct {
	Name        string   `json:"name"`
	Description *string  `json:"description,omitempty"`
	Roles       []string `json:"roles"`
	Grants      []Grant  `json:"grants"`
	Subject     any      `json:"subject,omitempty"`
	Disabled    bool     `json:"disabled"`
	HasToken    bool     `json:"hasToken"`
}

type UserInput struct {
	Name        string       `json:"name"`
	Description *string      `json:"description,omitempty"`
	Roles       []string     `json:"roles,omitempty"`
	Grants      []GrantInput `json:"grants,omitempty"`
	Subject     any          `json:"subject,omitempty"`
	Disabled    *bool        `json:"disabled,omitempty"`
	TokenHash   *string      `json:"tokenHash,omitempty"`
}

type UserToken struct {
	Token     string `json:"token"`
	TokenHash string `json:"tokenHash"`
}

type Validation struct {
	Ok          bool    `json:"ok"`
	Error       *string `json:"error,omitempty"`
	ContentHash *string `json:"contentHash,omitempty"`
	// Changes against the published revision that need a restart.
	RestartRequired []string `json:"restartRequired"`
}

type VisibilityInput struct {
	Draft    *DraftInput `json:"draft,omitempty"`
	Revision *string     `json:"revision,omitempty"`
	// A configured user name, or role:<name> to evaluate a role.
	User    string `json:"user"`
	Subject any    `json:"subject,omitempty"`
}

type Action string

const (
	ActionRead      Action = "READ"
	ActionCreate    Action = "CREATE"
	ActionUpdate    Action = "UPDATE"
	ActionDelete    Action = "DELETE"
	ActionExecute   Action = "EXECUTE"
	ActionAggregate Action = "AGGREGATE"
)

var AllAction = []Action{
	ActionRead,
	ActionCreate,
	ActionUpdate,
	ActionDelete,
	ActionExecute,
	ActionAggregate,
}

func (e Action) IsValid() bool {
	switch e {
	case ActionRead, ActionCreate, ActionUpdate, ActionDelete, ActionExecute, ActionAggregate:
		return true
	}
	return false
}

func (e Action) String() string {
	return string(e)
}

func (e *Action) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Action(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Action", str)
	}
	return nil
}

func (e Action) MarshalGQL(w io.Writer) {
	_, _ = fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Action) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Action) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ImportStatus string

const (
	// No configured entity reads this table.
	ImportStatusNew ImportStatus = "NEW"
	// An entity of the same datasource already reads this table.
	ImportStatusConfigured ImportStatus = "CONFIGURED"
)

var AllImportStatus = []ImportStatus{
	ImportStatusNew,
	ImportStatusConfigured,
}

func (e ImportStatus) IsValid() bool {
	switch e {
	case ImportStatusNew, ImportStatusConfigured:
		return true
	}
	return false
}

func (e ImportStatus) String() string {
	return string(e)
}

func (e *ImportStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ImportStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ImportStatus", str)
	}
	return nil
}

func (e ImportStatus) MarshalGQL(w io.Writer) {
	_, _ = fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ImportStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ImportStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type RevisionState string

const (
	RevisionStateDraft      RevisionState = "DRAFT"
	RevisionStatePublished  RevisionState = "PUBLISHED"
	RevisionStateSuperseded RevisionState = "SUPERSEDED"
	RevisionStateRolledBack RevisionState = "ROLLED_BACK"
)

var AllRevisionState = []RevisionState{
	RevisionStateDraft,
	RevisionStatePublished,
	RevisionStateSuperseded,
	RevisionStateRolledBack,
}

func (e RevisionState) IsValid() bool {
	switch e {
	case RevisionStateDraft, RevisionStatePublished, RevisionStateSuperseded, RevisionStateRolledBack:
		return true
	}
	return false
}

func (e RevisionState) String() string {
	return string(e)
}

func (e *RevisionState) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = RevisionState(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid RevisionState", str)
	}
	return nil
}

func (e RevisionState) MarshalGQL(w io.Writer) {
	_, _ = fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *RevisionState) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e RevisionState) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
