package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"
	"errors"
	"fmt"

	"github.com/nethinwei/sql-mcp-server/core/config"
	"github.com/nethinwei/sql-mcp-server/core/revision"
	"github.com/nethinwei/sql-mcp-server/x/admin/auth"
	"github.com/nethinwei/sql-mcp-server/x/bootstrap"
	"github.com/nethinwei/sql-mcp-server/x/configstore"
)

// CreateDraft is the resolver for the createDraft field.
func (r *mutationResolver) CreateDraft(ctx context.Context, draft DraftInput, comment *string) (*Revision, error) {
	p, err := auth.Require(ctx, auth.PermWrite)
	if err != nil {
		return nil, err
	}
	d, err := r.buildDraft(ctx, draft)
	if err != nil {
		return nil, err
	}
	rev, err := r.Store.Create(ctx, revision.Draft{
		ParentID: d.base.ID, Payload: d.payload, Author: p.Username, Comment: deref(comment),
	})
	if err != nil {
		return nil, err
	}
	auditAdmin(ctx, "createDraft", rev)
	return toRevision(rev), nil
}

// Publish is the resolver for the publish field.
func (r *mutationResolver) Publish(ctx context.Context, input PublishInput) (*Revision, error) {
	id, restartRequired, expectedPublished := input.ID, input.RestartRequired, input.ExpectedPublished
	p, err := auth.Require(ctx, auth.PermPublish)
	if err != nil {
		return nil, err
	}
	target, err := r.revisionByID(ctx, id)
	if err != nil {
		return nil, err
	}
	current, err := r.Store.Published(ctx)
	if err != nil && !errors.Is(err, revision.ErrNoPublished) {
		return nil, err
	}
	if err := checkExpectedPublished(current, expectedPublished); err != nil {
		return nil, err
	}
	if err := bootstrap.CheckPublishable(current, target, derefBool(restartRequired)); err != nil {
		return nil, err
	}
	rev, err := r.Store.Publish(ctx, target.ID, current.ID, revision.Meta{Author: p.Username})
	if err != nil {
		return nil, err
	}
	auditAdmin(ctx, "publish", rev)
	return toRevision(rev), nil
}

// Rollback is the resolver for the rollback field.
func (r *mutationResolver) Rollback(ctx context.Context, input RollbackInput) (*Revision, error) {
	to, restartRequired, comment := input.To, input.RestartRequired, input.Comment
	p, err := auth.Require(ctx, auth.PermPublish)
	if err != nil {
		return nil, err
	}
	current, err := r.Store.Published(ctx)
	if err != nil {
		return nil, err
	}
	var targetID int64
	if to != nil {
		if targetID, err = parseID(*to); err != nil {
			return nil, err
		}
	}
	all, err := r.Store.List(ctx, 0)
	if err != nil {
		return nil, err
	}
	chosen, err := revision.RollbackTarget(all, current, targetID)
	if err != nil {
		return nil, err
	}
	target, err := r.Store.Get(ctx, chosen.ID)
	if err != nil {
		return nil, err
	}
	if err := bootstrap.CheckPublishable(current, target, derefBool(restartRequired)); err != nil {
		return nil, err
	}
	rev, err := r.Store.Rollback(ctx, current.ID, target.ID, revision.Meta{Author: p.Username, Comment: deref(comment)})
	if err != nil {
		return nil, err
	}
	auditAdmin(ctx, "rollback", rev)
	return toRevision(rev), nil
}

// GenerateUserToken is the resolver for the generateUserToken field.
func (r *mutationResolver) GenerateUserToken(ctx context.Context) (*UserToken, error) {
	if _, err := auth.Require(ctx, auth.PermWrite); err != nil {
		return nil, err
	}
	token, err := newUserToken()
	if err != nil {
		return nil, err
	}
	return &UserToken{Token: token, TokenHash: config.TokenHash(token)}, nil
}

// CreateAdminAccount is the resolver for the createAdminAccount field.
func (r *mutationResolver) CreateAdminAccount(ctx context.Context, input AdminAccountInput) (*AdminAccount, error) {
	username, password, permissions := input.Username, input.Password, input.Permissions
	if _, err := auth.Require(ctx, auth.PermAccounts); err != nil {
		return nil, err
	}
	if err := auth.ValidateUsername(username); err != nil {
		return nil, err
	}
	if err := auth.ValidatePermissions(permissions); err != nil {
		return nil, err
	}
	if err := auth.ValidatePassword(password); err != nil {
		return nil, err
	}
	hash, err := auth.HashPassword(password)
	if err != nil {
		return nil, err
	}
	a, err := r.Accounts.CreateAdmin(ctx, configstore.AdminAccount{
		Username: username, PasswordHash: hash, Permissions: permissions,
	})
	if err != nil {
		return nil, err
	}
	return toAdminAccount(a), nil
}

// UpdateAdminAccount is the resolver for the updateAdminAccount field.
func (r *mutationResolver) UpdateAdminAccount(ctx context.Context, input AdminAccountUpdate) (*AdminAccount, error) {
	username, permissions, disabled := input.Username, input.Permissions, input.Disabled
	if _, err := auth.Require(ctx, auth.PermAccounts); err != nil {
		return nil, err
	}
	a, err := r.Accounts.GetAdmin(ctx, username)
	if err != nil {
		return nil, err
	}
	if permissions != nil {
		if err := auth.ValidatePermissions(permissions); err != nil {
			return nil, err
		}
		a.Permissions = permissions
	}
	if disabled != nil {
		a.Disabled = *disabled
	}
	if err := r.checkAccountManagers(ctx, a); err != nil {
		return nil, err
	}
	updated, err := r.Accounts.UpdateAdmin(ctx, a)
	if err != nil {
		return nil, err
	}
	return toAdminAccount(updated), nil
}

// SetAdminPassword is the resolver for the setAdminPassword field.
func (r *mutationResolver) SetAdminPassword(ctx context.Context, input SetAdminPasswordInput) (*AdminAccount, error) {
	username, password := input.Username, input.Password
	// Any signed-in administrator may change their own password; changing
	// another account's needs admin:accounts, like every account change.
	p, ok := auth.PrincipalFrom(ctx)
	if !ok {
		return nil, auth.ErrUnauthorized
	}
	if username != p.Username && !p.Has(auth.PermAccounts) {
		return nil, fmt.Errorf("%w: %s required to change another account's password", auth.ErrForbidden, auth.PermAccounts)
	}
	if err := auth.ValidatePassword(password); err != nil {
		return nil, err
	}
	a, err := r.Accounts.GetAdmin(ctx, username)
	if err != nil {
		return nil, err
	}
	if a.PasswordHash, err = auth.HashPassword(password); err != nil {
		return nil, err
	}
	updated, err := r.Accounts.UpdateAdmin(ctx, a)
	if err != nil {
		return nil, err
	}
	return toAdminAccount(updated), nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*AdminAccount, error) {
	p, ok := auth.PrincipalFrom(ctx)
	if !ok {
		return nil, auth.ErrUnauthorized
	}
	a, err := r.Accounts.GetAdmin(ctx, p.Username)
	if err != nil {
		return nil, err
	}
	return toAdminAccount(a), nil
}

// ServerStatus is the resolver for the serverStatus field.
func (r *queryResolver) ServerStatus(ctx context.Context) (*ServerStatus, error) {
	if _, err := auth.Require(ctx, auth.PermRead); err != nil {
		return nil, err
	}
	return serverStatus(r.Status), nil
}

// ConfigSchema is the resolver for the configSchema field.
func (r *queryResolver) ConfigSchema(ctx context.Context) (any, error) {
	if _, err := auth.Require(ctx, auth.PermRead); err != nil {
		return nil, err
	}
	return configSchema()
}

// Published is the resolver for the published field.
func (r *queryResolver) Published(ctx context.Context) (*Revision, error) {
	if _, err := auth.Require(ctx, auth.PermRead); err != nil {
		return nil, err
	}
	rev, err := r.Store.Published(ctx)
	if errors.Is(err, revision.ErrNoPublished) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	return toRevision(rev), nil
}

// Revision is the resolver for the revision field.
func (r *queryResolver) Revision(ctx context.Context, id string) (*Revision, error) {
	if _, err := auth.Require(ctx, auth.PermRead); err != nil {
		return nil, err
	}
	rev, err := r.revisionByID(ctx, id)
	if errors.Is(err, revision.ErrNotFound) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	return toRevision(rev), nil
}

// Revisions is the resolver for the revisions field.
func (r *queryResolver) Revisions(ctx context.Context, limit *int) ([]Revision, error) {
	if _, err := auth.Require(ctx, auth.PermRead); err != nil {
		return nil, err
	}
	n := 50
	if limit != nil {
		n = *limit
	}
	revs, err := r.Store.List(ctx, n)
	if err != nil {
		return nil, err
	}
	out := make([]Revision, 0, len(revs))
	for _, rev := range revs {
		out = append(out, *toRevision(rev))
	}
	return out, nil
}

// SchemaImport is the resolver for the schemaImport field.
func (r *queryResolver) SchemaImport(ctx context.Context, datasource string, schemas []string) (*SchemaImport, error) {
	if _, err := auth.Require(ctx, auth.PermWrite); err != nil {
		return nil, err
	}
	current, err := r.Store.Published(ctx)
	if err != nil {
		return nil, err
	}
	cfg, err := bootstrap.LoadRevision(current)
	if err != nil {
		return nil, err
	}
	if !hasDatasource(cfg, datasource) {
		return nil, fmt.Errorf("unknown datasource %q", datasource)
	}
	discovered, err := r.Introspect(ctx, datasource, schemas)
	if err != nil {
		return nil, fmt.Errorf("introspect %q: %w", datasource, err)
	}
	return buildSchemaImport(datasource, discovered, cfg), nil
}

// Validate is the resolver for the validate field.
func (r *queryResolver) Validate(ctx context.Context, draft DraftInput) (*Validation, error) {
	if _, err := auth.Require(ctx, auth.PermRead); err != nil {
		return nil, err
	}
	d, err := r.buildDraft(ctx, draft)
	if err != nil {
		msg := err.Error()
		return &Validation{Ok: false, Error: &msg, RestartRequired: []string{}}, nil
	}
	changes, err := r.restartChanges(ctx, d.cfg)
	if err != nil {
		return nil, err
	}
	hash := revision.Hash(d.payload)
	return &Validation{Ok: true, ContentHash: &hash, RestartRequired: changes}, nil
}

// Diff is the resolver for the diff field.
func (r *queryResolver) Diff(ctx context.Context, from string, to *string, draft *DraftInput) (string, error) {
	if _, err := auth.Require(ctx, auth.PermRead); err != nil {
		return "", err
	}
	a, err := r.revisionByID(ctx, from)
	if err != nil {
		return "", err
	}
	switch {
	case draft != nil:
		d, err := r.buildDraft(ctx, *draft)
		if err != nil {
			return "", err
		}
		return unifiedDiff(fmt.Sprintf("revision %d", a.ID), a.Payload, "draft", d.payload)
	case to != nil:
		b, err := r.revisionByID(ctx, *to)
		if err != nil {
			return "", err
		}
		return unifiedDiff(fmt.Sprintf("revision %d", a.ID), a.Payload, fmt.Sprintf("revision %d", b.ID), b.Payload)
	default:
		b, err := r.Store.Published(ctx)
		if err != nil {
			return "", err
		}
		return unifiedDiff(fmt.Sprintf("revision %d", a.ID), a.Payload, fmt.Sprintf("revision %d", b.ID), b.Payload)
	}
}

// Simulate is the resolver for the simulate field.
func (r *queryResolver) Simulate(ctx context.Context, input SimulationInput) (*Simulation, error) {
	draft, revision, subject := input.Draft, input.Revision, input.Subject
	if _, err := auth.Require(ctx, auth.PermRead); err != nil {
		return nil, err
	}
	cfg, err := r.simulationConfig(ctx, draft, revision)
	if err != nil {
		return nil, err
	}
	attrs, _ := normalizeJSON(subject).(map[string]any)
	if subject != nil && attrs == nil {
		return nil, errors.New("subject must be an object")
	}
	return simulate(ctx, cfg, input.User, input.Entity, input.Action, input.Fields, attrs)
}

// Visibility is the resolver for the visibility field.
func (r *queryResolver) Visibility(ctx context.Context, input VisibilityInput) ([]EntityVisibility, error) {
	if _, err := auth.Require(ctx, auth.PermRead); err != nil {
		return nil, err
	}
	cfg, err := r.simulationConfig(ctx, input.Draft, input.Revision)
	if err != nil {
		return nil, err
	}
	attrs, _ := normalizeJSON(input.Subject).(map[string]any)
	if input.Subject != nil && attrs == nil {
		return nil, errors.New("subject must be an object")
	}
	return visibility(ctx, cfg, input.User, attrs)
}

// AdminAccounts is the resolver for the adminAccounts field.
func (r *queryResolver) AdminAccounts(ctx context.Context) ([]AdminAccount, error) {
	if _, err := auth.Require(ctx, auth.PermAccounts); err != nil {
		return nil, err
	}
	all, err := r.Accounts.ListAdmins(ctx)
	if err != nil {
		return nil, err
	}
	out := make([]AdminAccount, 0, len(all))
	for _, a := range all {
		out = append(out, *toAdminAccount(a))
	}
	return out, nil
}

// Config is the resolver for the config field.
func (r *revisionResolver) Config(ctx context.Context, obj *Revision) (*Configuration, error) {
	rev, err := r.withPayload(ctx, obj)
	if err != nil {
		return nil, err
	}
	cfg, err := bootstrap.LoadRevision(rev)
	if err != nil {
		return nil, err
	}
	return toConfiguration(cfg, rev.Payload)
}

// Yaml is the resolver for the yaml field.
func (r *revisionResolver) Yaml(ctx context.Context, obj *Revision) (string, error) {
	rev, err := r.withPayload(ctx, obj)
	if err != nil {
		return "", err
	}
	if err := rev.Verify(); err != nil {
		return "", err
	}
	return string(rev.Payload), nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Revision returns RevisionResolver implementation.
func (r *Resolver) Revision() RevisionResolver { return &revisionResolver{r} }

type (
	mutationResolver struct{ *Resolver }
	queryResolver    struct{ *Resolver }
	revisionResolver struct{ *Resolver }
)
