-- Generated by fixtures/v4/generator (seed=1 scale=1). Do not edit;
-- run `make fixtures-v4` to regenerate.
DROP TABLE IF EXISTS wl_currencies;
CREATE TABLE wl_currencies (
	id integer NOT NULL,
	code varchar(64) NOT NULL,
	name varchar(255) NOT NULL,
	minor_unit_scale integer NOT NULL,
	PRIMARY KEY (id)
);

DROP TABLE IF EXISTS wl_countries;
CREATE TABLE wl_countries (
	id integer NOT NULL,
	code varchar(64) NOT NULL,
	name varchar(255) NOT NULL,
	region varchar(64) NOT NULL,
	PRIMARY KEY (id)
);

DROP TABLE IF EXISTS wl_organizations;
CREATE TABLE wl_organizations (
	id integer NOT NULL,
	name varchar(255) NOT NULL,
	country_code varchar(64) NOT NULL,
	created_at date NOT NULL,
	PRIMARY KEY (id)
);

DROP TABLE IF EXISTS wl_applications;
CREATE TABLE wl_applications (
	id integer NOT NULL,
	organization_id integer NOT NULL,
	name varchar(64) NOT NULL,
	currency_code varchar(64) NOT NULL,
	status varchar(64) NOT NULL,
	PRIMARY KEY (id)
);

DROP TABLE IF EXISTS wl_users;
CREATE TABLE wl_users (
	id integer NOT NULL,
	email varchar(255) NOT NULL,
	display_name varchar(255) NOT NULL,
	created_at date NOT NULL,
	PRIMARY KEY (id)
);

DROP TABLE IF EXISTS wl_customers;
CREATE TABLE wl_customers (
	id integer NOT NULL,
	organization_id integer NOT NULL,
	email varchar(255) NOT NULL,
	country_code varchar(64) NOT NULL,
	created_at date NOT NULL,
	deleted_at datetime,
	PRIMARY KEY (id)
);

DROP TABLE IF EXISTS wl_products;
CREATE TABLE wl_products (
	id integer NOT NULL,
	application_id integer NOT NULL,
	name varchar(255) NOT NULL,
	product_type varchar(64) NOT NULL,
	status varchar(64) NOT NULL,
	PRIMARY KEY (id)
);

DROP TABLE IF EXISTS wl_product_price_versions;
CREATE TABLE wl_product_price_versions (
	id integer NOT NULL,
	product_id integer NOT NULL,
	price_minor bigint NOT NULL,
	currency_code varchar(64) NOT NULL,
	valid_from date NOT NULL,
	valid_to date,
	PRIMARY KEY (id)
);

DROP TABLE IF EXISTS wl_orders;
CREATE TABLE wl_orders (
	id integer NOT NULL,
	application_id integer NOT NULL,
	customer_id integer NOT NULL,
	status varchar(64) NOT NULL,
	currency_code varchar(64) NOT NULL,
	total_minor bigint NOT NULL,
	created_at datetime NOT NULL,
	confirmed_at datetime,
	cancelled_at datetime,
	completed_at datetime,
	PRIMARY KEY (id)
);

DROP TABLE IF EXISTS wl_order_items;
CREATE TABLE wl_order_items (
	id integer NOT NULL,
	order_id integer NOT NULL,
	product_id integer NOT NULL,
	quantity integer NOT NULL,
	unit_price_minor bigint NOT NULL,
	currency_code varchar(64) NOT NULL,
	PRIMARY KEY (id)
);
