-- Generated by fixtures/v4/generator (seed=1 scale=1). Do not edit;
-- run `make fixtures-v4` to regenerate.
DROP TABLE IF EXISTS wl_payment_channels;
CREATE TABLE wl_payment_channels (
	id integer NOT NULL,
	name varchar(64) NOT NULL,
	status varchar(64) NOT NULL,
	PRIMARY KEY (id)
);

DROP TABLE IF EXISTS wl_routing_rule_versions;
CREATE TABLE wl_routing_rule_versions (
	id integer NOT NULL,
	rule_name varchar(64) NOT NULL,
	strategy text NOT NULL,
	valid_from date NOT NULL,
	valid_to date,
	PRIMARY KEY (id)
);

DROP TABLE IF EXISTS wl_payment_intents;
CREATE TABLE wl_payment_intents (
	id integer NOT NULL,
	order_id integer NOT NULL,
	status varchar(64) NOT NULL,
	amount_minor bigint NOT NULL,
	fee_minor bigint NOT NULL,
	currency_code varchar(64) NOT NULL,
	final_channel_id integer,
	created_at timestamp NOT NULL,
	completed_at timestamp,
	PRIMARY KEY (id)
);

DROP TABLE IF EXISTS wl_payment_attempts;
CREATE TABLE wl_payment_attempts (
	id integer NOT NULL,
	intent_id integer NOT NULL,
	attempt_no integer NOT NULL,
	channel_id integer NOT NULL,
	status varchar(64) NOT NULL,
	channel_status varchar(64) NOT NULL,
	amount_minor bigint NOT NULL,
	created_at timestamp NOT NULL,
	PRIMARY KEY (id)
);

DROP TABLE IF EXISTS wl_routing_decisions;
CREATE TABLE wl_routing_decisions (
	id integer NOT NULL,
	attempt_id integer NOT NULL,
	rule_version_id integer NOT NULL,
	selected_channel_id integer NOT NULL,
	reason varchar(64) NOT NULL,
	PRIMARY KEY (id)
);

DROP TABLE IF EXISTS wl_refunds;
CREATE TABLE wl_refunds (
	id integer NOT NULL,
	intent_id integer NOT NULL,
	kind varchar(64) NOT NULL,
	amount_minor bigint NOT NULL,
	currency_code varchar(64) NOT NULL,
	status varchar(64) NOT NULL,
	created_at timestamp NOT NULL,
	PRIMARY KEY (id)
);

DROP TABLE IF EXISTS wl_channel_callbacks;
CREATE TABLE wl_channel_callbacks (
	id integer NOT NULL,
	channel_id integer NOT NULL,
	attempt_id integer NOT NULL,
	external_event_id varchar(64) NOT NULL,
	event_type varchar(64) NOT NULL,
	occurred_at timestamp NOT NULL,
	received_at timestamp NOT NULL,
	processed_at timestamp,
	PRIMARY KEY (id)
);
