-- Generated by fixtures/v4/generator (seed=1 scale=1). Do not edit;
-- run `make fixtures-v4` to regenerate.
DROP TABLE IF EXISTS wl_agencies;
CREATE TABLE wl_agencies (
	id integer NOT NULL,
	name text NOT NULL,
	PRIMARY KEY (id)
);

DROP TABLE IF EXISTS wl_creators;
CREATE TABLE wl_creators (
	id integer NOT NULL,
	display_name text NOT NULL,
	agency_id integer,
	signed_at date,
	PRIMARY KEY (id)
);

DROP TABLE IF EXISTS wl_live_rooms;
CREATE TABLE wl_live_rooms (
	id integer NOT NULL,
	creator_id integer NOT NULL,
	title text NOT NULL,
	PRIMARY KEY (id)
);

DROP TABLE IF EXISTS wl_live_sessions;
CREATE TABLE wl_live_sessions (
	id integer NOT NULL,
	room_id integer NOT NULL,
	started_at timestamp NOT NULL,
	ended_at timestamp NOT NULL,
	PRIMARY KEY (id)
);

DROP TABLE IF EXISTS wl_gift_definitions;
CREATE TABLE wl_gift_definitions (
	id integer NOT NULL,
	name text NOT NULL,
	PRIMARY KEY (id)
);

DROP TABLE IF EXISTS wl_gift_price_versions;
CREATE TABLE wl_gift_price_versions (
	id integer NOT NULL,
	gift_id integer NOT NULL,
	price_stars bigint NOT NULL,
	valid_from date NOT NULL,
	valid_to date,
	PRIMARY KEY (id)
);

DROP TABLE IF EXISTS wl_revenue_share_rule_versions;
CREATE TABLE wl_revenue_share_rule_versions (
	id integer NOT NULL,
	creator_bps integer NOT NULL,
	agency_bps integer NOT NULL,
	valid_from date NOT NULL,
	valid_to date,
	PRIMARY KEY (id)
);

DROP TABLE IF EXISTS wl_gift_events;
CREATE TABLE wl_gift_events (
	id integer NOT NULL,
	session_id integer NOT NULL,
	creator_id integer NOT NULL,
	gift_id integer NOT NULL,
	quantity integer NOT NULL,
	total_stars bigint NOT NULL,
	status varchar(64) NOT NULL,
	dedup_of integer,
	occurred_at timestamp NOT NULL,
	PRIMARY KEY (id)
);

DROP TABLE IF EXISTS wl_revenue_splits;
CREATE TABLE wl_revenue_splits (
	id integer NOT NULL,
	gift_event_id integer NOT NULL,
	creator_id integer NOT NULL,
	rule_version_id integer NOT NULL,
	creator_stars bigint NOT NULL,
	agency_stars bigint NOT NULL,
	platform_stars bigint NOT NULL,
	occurred_at timestamp NOT NULL,
	PRIMARY KEY (id)
);

DROP TABLE IF EXISTS wl_creator_settlements;
CREATE TABLE wl_creator_settlements (
	id integer NOT NULL,
	creator_id integer NOT NULL,
	period_start date NOT NULL,
	period_end date NOT NULL,
	settled_stars bigint NOT NULL,
	status varchar(64) NOT NULL,
	settled_at timestamp NOT NULL,
	PRIMARY KEY (id)
);
