package workload

import (
	"fmt"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"
)

// moduleDir maps a module name to its directory under fixtures/v4
// (industry verticals live under verticals/).
func moduleDir(module string) string {
	if module == "live-monetization" {
		return "verticals/live-monetization"
	}
	return module
}

// taskModule maps a task-id prefix to the owning module.
var taskModule = map[string]string{
	"commerce": "commerce-core",
	"payments": "payment-orchestration",
	"ledger":   "ledger-settlement",
	"live":     "live-monetization",
}

// Artifacts renders every generated checked-in file keyed by path relative
// to fixtures/v4. Map iteration order does not matter: each file's content
// is independently deterministic.
func Artifacts(cfg Config) map[string]string {
	d := Generate(cfg)
	out := map[string]string{}

	header := fmt.Sprintf(
		"-- Generated by fixtures/v4/generator (seed=%d scale=%d). Do not edit;\n"+
			"-- run `make fixtures-v4` to regenerate.\n", cfg.Seed, cfg.Scale)

	modules := []string{"commerce-core", "payment-orchestration", "ledger-settlement", "live-monetization"}
	for _, module := range modules {
		addModuleSQL(out, d, module, header)
	}

	for id, exp := range Expected(cfg) {
		module, _, _ := strings.Cut(id, ".")
		dir := moduleDir(taskModule[module])
		out[fmt.Sprintf("%s/expected/%s.csv", dir, id)] = renderCSV(exp.Result)
	}

	profile, err := yaml.Marshal(d.Profile())
	if err != nil {
		panic(err) // profile is built from static maps; marshal cannot fail
	}
	yamlHeader := strings.ReplaceAll(header, "--", "#")
	out["profiles/default.yaml"] = yamlHeader + string(profile)
	diagnosticProfile, err := yaml.Marshal(d.DiagnosticProfile())
	if err != nil {
		panic(err)
	}
	out["profiles/diagnostic.yaml"] = yamlHeader + string(diagnosticProfile)

	for _, module := range modules {
		out[moduleDir(module)+"/policies/entities.yaml"] =
			yamlHeader + modulePolicies(d, module)
	}
	return out
}

// addModuleSQL emits one module's schema and seed files per dialect family
// (MySQL and OceanBase render identically and share one file).
func addModuleSQL(out map[string]string, d *Dataset, module, header string) {
	dir := moduleDir(module)
	for _, dialect := range []string{DialectPostgres, DialectMySQL} {
		var ddl, seed []string
		for _, t := range d.Tables {
			if t.Module != module {
				continue
			}
			stmts := t.StatementsIn(dialect, "")
			ddl = append(ddl, stmts[0]+";\n"+stmts[1]+";")
			for _, s := range stmts[2:] {
				seed = append(seed, s+";")
			}
		}
		suffix := dialect
		if dialect == DialectMySQL {
			suffix = "mysql-oceanbase"
		}
		out[fmt.Sprintf("%s/schema/%s.sql", dir, suffix)] = header + strings.Join(ddl, "\n\n") + "\n"
		out[fmt.Sprintf("%s/seed/%s.sql", dir, suffix)] = header + strings.Join(seed, "\n") + "\n"
	}
}

// modulePolicies extracts one module's entity configurations (the RBAC,
// mask, and relationship examples) from the combined profile.
func modulePolicies(d *Dataset, module string) string {
	profile := d.Profile()
	all := profile["entities"].([]any)
	names := map[string]bool{}
	for _, t := range d.Tables {
		if t.Module == module {
			names[t.Entity] = true
		}
	}
	var picked []any
	for _, e := range all {
		if names[e.(map[string]any)["name"].(string)] {
			picked = append(picked, e)
		}
	}
	rendered, err := yaml.Marshal(map[string]any{"entities": picked})
	if err != nil {
		panic(err)
	}
	return string(rendered)
}

// renderCSV renders an expected result table; the evidence grading channel
// parses it back.
func renderCSV(r *ResultTable) string {
	var b strings.Builder
	b.WriteString(strings.Join(r.Columns, ","))
	b.WriteByte('\n')
	for _, row := range r.Rows {
		b.WriteString(strings.Join(row, ","))
		b.WriteByte('\n')
	}
	return b.String()
}

// ExpectedTaskIDs lists every task id with a computed expectation, sorted.
func ExpectedTaskIDs(cfg Config) []string {
	ids := make([]string, 0)
	for id := range Expected(cfg) {
		ids = append(ids, id)
	}
	sort.Strings(ids)
	return ids
}
